layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: https://www.facebook.com/Wayne.Gakuo
  # behance: your_username
  # dribbble: your_username
  # hackerrank: your_username
  instagram: https://www.instagram.com/wayne_gakuo
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/waynegakuo/
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: https://twitter.com/wayne_gakuo
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Vue JS
    web_url: https://github.com/topics/angular
    image_url: https://repository-images.githubusercontent.com/24195339/87018c00-694b-11e9-8b5f-c34826306d36
    
  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://repository-images.githubusercontent.com/126577260/3c924980-61ac-11e9-8e4e-6e50e0cec366
    
  - name: Laravel
    web_url: https://github.com/topics/laravel
    image_url: https://raw.githubusercontent.com/github/explore/56a826d05cf762b2b50ecbe7d492a839b04f3fbf/topics/laravel/laravel.png